# Generated by Django 6.0.7 on 2026-07-11 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=list, help_text='Posición y tamaño de los paneles del dashboard.', verbose_name='Distribución de widgets')),
                ('chart_types', models.JSONField(blank=True, default=dict, help_text='Tipo de gráfico seleccionado para cada panel.', verbose_name='Tipos de gráficos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia del dashboard',
                'verbose_name_plural': 'Preferencias del dashboard',
                'ordering': ['-updated_at'],
            },
        ),
    ]
