# Generated by Django 6.0.7 on 2026-07-18 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DEVICE_OFFLINE', 'Equipo fuera de línea'), ('STOCK_OUT', 'Consumible sin stock'), ('LOW_STOCK', 'Consumible con stock bajo'), ('CONTRACT_EXPIRING', 'Contrato próximo a vencer'), ('GENERAL', 'Notificación general')], default='GENERAL', max_length=30, verbose_name='Tipo de notificación')),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('DANGER', 'Crítica'), ('SUCCESS', 'Correcta')], default='INFO', max_length=20, verbose_name='Nivel')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Enlace interno')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de objeto')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Identificador del objeto')),
                ('unique_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Clave única')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'is_active'], name='notificatio_recipie_f67581_idx'), models.Index(fields=['notification_type', 'is_active'], name='notificatio_notific_f20333_idx')],
            },
        ),
    ]
