# Generated by Django 6.0.7 on 2026-07-18 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reapertura'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Reabierta por'),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución'),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por'),
        ),
    ]
