# Generated by Django 6.0.7 on 2026-08-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_unique_notification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DEVICE_OFFLINE', 'Equipo fuera de línea'), ('STOCK_OUT', 'Consumible sin stock'), ('LOW_STOCK', 'Consumible con stock bajo'), ('CONTRACT_EXPIRING', 'Contrato próximo a vencer'), ('TICKET_ASSIGNED', 'Ticket asignado'), ('TICKET_COMMENT', 'Nueva respuesta en ticket'), ('GENERAL', 'Notificación general')], default='GENERAL', max_length=30, verbose_name='Tipo de notificación'),
        ),
    ]
