# Generated by Django 6.0.7 on 2026-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('primary_color', models.CharField(default='#0a1a3a', max_length=20, verbose_name='Color principal')),
                ('secondary_color', models.CharField(default='#f68b1e', max_length=20, verbose_name='Color secundario')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='departments/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
