# Generated by Django 6.0.7 on 2026-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sla_hours',
            field=models.IntegerField(default=24, help_text='Tiempo máximo de respuesta en horas para este departamento.', verbose_name='Horas de SLA'),
        ),
    ]
