# Generated by Django 6.0.7 on 2026-07-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_sla_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('icon', models.CharField(blank=True, help_text='Clase de Bootstrap Icons (ej: bi-printer, bi-laptop, bi-lightning)', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='core.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Categoría de ticket',
                'verbose_name_plural': 'Categorías de tickets',
                'ordering': ['department', 'order', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
    ]
