# Generated by Django 6.0.7 on 2026-07-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Comentario del sistema'),
        ),
    ]
