# Generated by Django 6.0.7 on 2026-07-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketcomment_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='comment_type',
            field=models.CharField(choices=[('COMMENT', 'Comentario'), ('ASSIGN', 'Asignación'), ('STATUS', 'Cambio de estado'), ('ATTACHMENT', 'Adjunto'), ('SYSTEM', 'Sistema')], default='COMMENT', max_length=20, verbose_name='Tipo de comentario'),
        ),
    ]
