# Generated by Django 6.0.7 on 2026-07-10 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketcomment_comment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='tickets/attachments/%Y/%m/', verbose_name='Archivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('content_type', models.CharField(blank=True, max_length=150, verbose_name='Tipo de archivo')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'ordering': ['created_at'],
            },
        ),
    ]
