# Generated by Django 6.0.7 on 2026-07-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tickets', '0005_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='inventory.asset', verbose_name='Equipo relacionado'),
        ),
    ]
