# Generated by Django 6.0.7 on 2026-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_group',
            field=models.CharField(choices=[('SUPPORT', 'Soporte'), ('SYSTEMS', 'Sistemas')], default='SUPPORT', max_length=20, verbose_name='Grupo asignado'),
        ),
    ]
