# Generated by Django 6.0.7 on 2026-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite (SLA)'),
        ),
    ]
