# Generated by Django 6.0.7 on 2026-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(blank=True, help_text='OK, WARNING o EXPIRED', max_length=20, null=True, verbose_name='Estado del SLA'),
        ),
    ]
