# Generated by Django 6.0.7 on 2026-07-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticketcategory'),
        ('tickets', '0010_ticket_sla_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Red'), ('PRINTER', 'Impresora'), ('ELECTRICITY', 'Electricidad'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del ticket')),
                ('description', models.TextField(verbose_name='Descripción del ticket')),
                ('icon', models.CharField(blank=True, default='bi-tag', help_text='Clase de Bootstrap Icons (ej: bi-printer, bi-laptop, bi-lightning)', max_length=50, verbose_name='Icono')),
                ('label', models.CharField(blank=True, help_text='Texto corto que aparece debajo (ej: Hardware, Red, Electricidad)', max_length=50, verbose_name='Etiqueta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_actions', to='core.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Acceso rápido',
                'verbose_name_plural': 'Accesos rápidos',
                'ordering': ['department', 'order', 'title'],
            },
        ),
    ]
