# Generated by Django 6.0.7 on 2026-07-30 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_category_quickaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_system', models.CharField(max_length=100, verbose_name='Sistema solicitado')),
                ('operation', models.CharField(choices=[('USER_CREATION', 'Alta de usuario'), ('USER_DELETION', 'Baja de usuario'), ('USER_MODIFICATION', 'Modificación de usuario'), ('PERMISSION_CHANGE', 'Asignación o modificación de permisos')], max_length=30, verbose_name='Tipo de operación')),
                ('affected_employee', models.CharField(max_length=200, verbose_name='Funcionario afectado')),
                ('employee_number', models.CharField(max_length=50, verbose_name='Legajo')),
                ('employee_department', models.CharField(max_length=150, verbose_name='Departamento del funcionario')),
                ('employee_position', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('requested_permissions', models.TextField(blank=True, verbose_name='Permisos solicitados')),
                ('justification', models.TextField(verbose_name='Justificación')),
                ('authorizing_director', models.CharField(max_length=200, verbose_name='Director autorizante')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('authorization_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_FORM', 'Pendiente de formulario'), ('FORM_ATTACHED', 'Formulario adjuntado'), ('PENDING_VALIDATION', 'Pendiente de validación'), ('AUTHORIZED', 'Autorizado para procesar'), ('REJECTED', 'Formulario rechazado')], default='DRAFT', max_length=30, verbose_name='Estado de autorización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_access_request', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Solicitud de acceso a sistema',
                'verbose_name_plural': 'Solicitudes de acceso a sistemas',
                'ordering': ['-created_at'],
            },
        ),
    ]
