# Generated by Django 6.0.7 on 2026-07-30 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_systemaccessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='tickets/authorization_forms/%Y/%m/', verbose_name='Formulario firmado')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('content_type', models.CharField(blank=True, max_length=150, verbose_name='Tipo de archivo')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pendiente de validación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('REPLACED', 'Reemplazado')], default='PENDING', max_length=20, verbose_name='Estado de validación')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo del rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_documents', to='tickets.systemaccessrequest', verbose_name='Solicitud de acceso')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_authorization_documents', to=settings.AUTH_USER_MODEL, verbose_name='Adjuntado por')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_authorization_documents', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Documento de autorización',
                'verbose_name_plural': 'Documentos de autorización',
                'ordering': ['-version', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('access_request', 'version'), name='unique_authorization_document_version')],
            },
        ),
    ]
