# Generated by Django 6.0.7 on 2026-07-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_authorizationdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemaccessrequest',
            options={'ordering': ['-created_at'], 'permissions': [('validate_access_request', 'Puede validar solicitudes de acceso')], 'verbose_name': 'Solicitud de acceso a sistema', 'verbose_name_plural': 'Solicitudes de acceso a sistemas'},
        ),
    ]
