# Generated by Django 6.0.7 on 2026-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_sync_assigned_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignment_origin',
            field=models.CharField(choices=[('AUTO', 'Automática'), ('MANUAL', 'Manual'), ('UNKNOWN', 'Desconocida')], default='UNKNOWN', max_length=20, verbose_name='Origen de la asignación'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='auto_rebalance_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueo de redistribución automática'),
        ),
    ]
