# Generated by Django 6.0.7 on 2026-08-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_assignment_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reactivation_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solicitud de reactivación'),
        ),
    ]
