# Generated by Django 6.0.7 on 2026-08-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0014_alter_printingdevice_options_printingdevice_branch_and_more'),
        ('tickets', '0020_localize_standard_permission_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='printing_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='printing.printingdevice', verbose_name='Equipo de impresión tercerizado'),
        ),
    ]
