# Generated by Django 6.0.7 on 2026-07-17 11:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_asset_branch_alter_asset_assigned_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('PRINTER', 'Impresora'), ('MULTIFUNCTION', 'Multifuncional'), ('PHOTOCOPIER', 'Fotocopiadora'), ('SCANNER', 'Escáner')], default='PRINTER', max_length=20, verbose_name='Tipo de equipo')),
                ('technology', models.CharField(choices=[('LASER', 'Láser'), ('INKJET', 'Inyección de tinta'), ('THERMAL', 'Térmica'), ('OTHER', 'Otra')], default='LASER', max_length=20, verbose_name='Tecnología')),
                ('color_mode', models.CharField(choices=[('MONOCHROME', 'Monocromática'), ('COLOR', 'Color')], default='MONOCHROME', max_length=20, verbose_name='Modo de impresión')),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Propio'), ('RENTED', 'Alquilado'), ('LOANED', 'En préstamo'), ('LEASING', 'Leasing')], default='OWNED', max_length=20, verbose_name='Modalidad de propiedad')),
                ('supports_duplex', models.BooleanField(default=False, verbose_name='Impresión doble faz')),
                ('supports_network', models.BooleanField(default=True, verbose_name='Conectado a red')),
                ('supports_scan', models.BooleanField(default=False, verbose_name='Permite escanear')),
                ('supports_copy', models.BooleanField(default=False, verbose_name='Permite copiar')),
                ('supports_fax', models.BooleanField(default=False, verbose_name='Permite fax')),
                ('web_interface_url', models.URLField(blank=True, verbose_name='Dirección de administración web')),
                ('network_port', models.PositiveIntegerField(default=9100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puerto de red')),
                ('snmp_enabled', models.BooleanField(default=False, verbose_name='SNMP habilitado')),
                ('snmp_community', models.CharField(blank=True, max_length=100, verbose_name='Comunidad SNMP')),
                ('monthly_print_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite mensual de impresiones')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printing_device', to='inventory.asset', verbose_name='Activo')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_printing_devices', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del equipo')),
            ],
            options={
                'verbose_name': 'Equipo de impresión',
                'verbose_name_plural': 'Equipos de impresión',
                'ordering': ['asset'],
            },
        ),
    ]
