# Generated by Django 6.0.7 on 2026-07-17 11:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Número de contrato')),
                ('contract_type', models.CharField(choices=[('RENTAL', 'Alquiler'), ('LEASING', 'Leasing'), ('MAINTENANCE', 'Mantenimiento'), ('LOAN', 'Préstamo'), ('OTHER', 'Otro')], default='RENTAL', max_length=20, verbose_name='Tipo de contrato')),
                ('provider', models.CharField(max_length=150, verbose_name='Proveedor')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo mensual')),
                ('included_prints_bw', models.PositiveIntegerField(default=0, verbose_name='Impresiones B/N incluidas')),
                ('included_prints_color', models.PositiveIntegerField(default=0, verbose_name='Impresiones color incluidas')),
                ('excess_cost_bw', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo excedente B/N')),
                ('excess_cost_color', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo excedente color')),
                ('response_time_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de respuesta SLA en horas')),
                ('resolution_time_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de resolución SLA en horas')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre del contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono del contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo del contacto')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('EXPIRED', 'Vencido'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('devices', models.ManyToManyField(blank=True, related_name='contracts', to='printing.printingdevice', verbose_name='Equipos incluidos')),
            ],
            options={
                'verbose_name': 'Contrato de impresión',
                'verbose_name_plural': 'Contratos de impresión',
                'ordering': ['-start_date', 'contract_number'],
            },
        ),
    ]
