# Generated by Django 6.0.7 on 2026-07-17 13:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_printingcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del consumible')),
                ('consumable_type', models.CharField(choices=[('TONER', 'Tóner'), ('INK', 'Tinta'), ('DRUM', 'Unidad de imagen'), ('FUSER', 'Unidad de fusión'), ('WASTE_TONER', 'Tóner residual'), ('OTHER', 'Otro')], default='TONER', max_length=20, verbose_name='Tipo de consumible')),
                ('reference_code', models.CharField(max_length=100, unique=True, verbose_name='Código de referencia')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, help_text='Ej: Negro, Cian, Magenta, Amarillo', max_length=50, verbose_name='Color')),
                ('estimated_yield_pages', models.PositiveIntegerField(blank=True, help_text='Número de páginas estimadas que imprime este consumible.', null=True, verbose_name='Rendimiento estimado (páginas)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('min_stock_level', models.PositiveIntegerField(default=5, verbose_name='Nivel mínimo de stock')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Consumible',
                'verbose_name_plural': 'Consumibles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('COMPATIBLE', 'Compatible'), ('ALTERNATIVE', 'Alternativo')], default='ORIGINAL', max_length=20, verbose_name='Tipo de compatibilidad')),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si es el consumible recomendado para este equipo.', verbose_name='Consumible principal')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_compatibilities', to='printing.consumable', verbose_name='Consumible')),
                ('printing_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_compatibilities', to='printing.printingdevice', verbose_name='Equipo de impresión')),
            ],
            options={
                'verbose_name': 'Compatibilidad de consumible',
                'verbose_name_plural': 'Compatibilidades de consumibles',
                'ordering': ['printing_device', 'consumable'],
                'constraints': [models.UniqueConstraint(fields=('printing_device', 'consumable'), name='unique_printing_device_consumable')],
            },
        ),
    ]
