# Generated by Django 6.0.7 on 2026-07-17 14:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_consumable_consumablecompatibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('ISSUE', 'Salida'), ('CONSUMPTION', 'Consumo en equipo'), ('RETURN', 'Devolución'), ('POSITIVE_ADJUSTMENT', 'Ajuste positivo'), ('NEGATIVE_ADJUSTMENT', 'Ajuste negativo'), ('TRANSFER', 'Transferencia'), ('WRITE_OFF', 'Baja')], max_length=30, verbose_name='Tipo de movimiento')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del movimiento')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario')),
                ('source_location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación de origen')),
                ('destination_location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación de destino')),
                ('document_reference', models.CharField(blank=True, help_text='Factura, remisión, orden de trabajo u otro comprobante.', max_length=100, verbose_name='Documento de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='printing.consumable', verbose_name='Consumible')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printing_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('printing_device', models.ForeignKey(blank=True, help_text='Completar cuando el consumible se instale o utilice en un equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_movements', to='printing.printingdevice', verbose_name='Equipo de impresión')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
