# Generated by Django 6.0.7 on 2026-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_stockmovement'),
    ]

    operations = [
        # Agregar los campos nuevos
        migrations.AddField(
            model_name='consumable',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock inicial'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='maximum_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock máximo'),
        ),
        # Eliminar los campos antiguos
        migrations.RemoveField(
            model_name='consumable',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='min_stock_level',
        ),
    ]