# Generated by Django 6.0.7 on 2026-07-17 19:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0005_fix_consumable_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='maximum_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Si se define, alerta cuando se supera.', null=True, verbose_name='Stock máximo'),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de lectura')),
                ('total_counter', models.PositiveBigIntegerField(default=0, verbose_name='Contador total')),
                ('black_white_counter', models.PositiveBigIntegerField(default=0, verbose_name='Contador blanco y negro')),
                ('color_counter', models.PositiveBigIntegerField(default=0, verbose_name='Contador color')),
                ('copy_counter', models.PositiveBigIntegerField(default=0, verbose_name='Contador de copias')),
                ('scan_counter', models.PositiveBigIntegerField(default=0, verbose_name='Contador de escaneos')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('printing_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='printing.printingdevice', verbose_name='Equipo de impresión')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printing_meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Lectura de contador',
                'verbose_name_plural': 'Lecturas de contadores',
                'ordering': ['-reading_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('printing_device', 'reading_date'), name='unique_device_meter_reading_date')],
            },
        ),
    ]
