# Generated by Django 6.0.7 on 2026-07-17 21:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0006_alter_consumable_maximum_stock_meterreading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('INSPECTION', 'Inspección'), ('CLEANING', 'Limpieza'), ('PART_REPLACEMENT', 'Cambio de repuesto'), ('OTHER', 'Otro')], default='PREVENTIVE', max_length=30, verbose_name='Tipo de mantenimiento')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20, verbose_name='Estado')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('performed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('technician_name', models.CharField(blank=True, max_length=150, verbose_name='Técnico responsable')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='Proveedor o empresa técnica')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('solution', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('replaced_parts', models.TextField(blank=True, help_text='Ejemplo: fusor, rodillo, tambor, unidad de imagen.', verbose_name='Repuestos reemplazados')),
                ('meter_counter', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Contador del equipo al realizar el trabajo')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de mano de obra')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de repuestos')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('printing_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='printing.printingdevice', verbose_name='Equipo de impresión')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printing_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Mantenimiento de impresión',
                'verbose_name_plural': 'Mantenimientos de impresión',
                'ordering': ['-performed_date', '-scheduled_date', '-created_at'],
            },
        ),
    ]
