# Generated by Django 6.0.7 on 2026-07-22 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0007_maintenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingDeviceNetworkDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Dirección IP detectada')),
                ('detected_mac', models.CharField(blank=True, max_length=17, verbose_name='Dirección MAC detectada')),
                ('switch_name', models.CharField(blank=True, max_length=150, verbose_name='Switch detectado')),
                ('switch_port', models.CharField(blank=True, max_length=50, verbose_name='Puerto del switch')),
                ('vlan', models.CharField(blank=True, max_length=50, verbose_name='VLAN')),
                ('detected_location', models.CharField(blank=True, help_text='Ubicación física asociada al switch y puerto donde fue detectado el equipo.', max_length=255, verbose_name='Ubicación detectada')),
                ('detection_source', models.CharField(blank=True, help_text='Ejemplo: SNMP, tabla MAC del switch, servidor DHCP o detección manual.', max_length=100, verbose_name='Origen de la detección')),
                ('is_current', models.BooleanField(default=True, verbose_name='Detección actual')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de detección')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('printing_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_detections', to='printing.printingdevice', verbose_name='Equipo de impresión')),
            ],
            options={
                'verbose_name': 'Detección de red de equipo de impresión',
                'verbose_name_plural': 'Detecciones de red de equipos de impresión',
                'ordering': ['-detected_at'],
            },
        ),
    ]
