# Generated by Django 5.2.4 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_localize_standard_permission_names"),
        ("printing", "0009_localize_standard_permission_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="stock_product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_consumable",
                to="inventory.stockproduct",
                verbose_name="Producto de stock",
            ),
        ),
    ]
