# Generated by Django 6.0.7 on 2026-08-19 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_technicianavailabilityrequest"),
        ("inventory", "0013_localize_standard_permission_names"),
        ("printing", "0010_consumable_stock_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumableStockMigrationBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(choices=[("DRAFT", "Borrador"), ("IN_REVIEW", "En revisión"), ("COMPLETED", "Completado"), ("CANCELLED", "Cancelado")], default="DRAFT", max_length=12)),
                ("notes", models.TextField(blank=True)),
                ("total_items", models.PositiveIntegerField(default=0, editable=False)),
                ("pending_items", models.PositiveIntegerField(default=0, editable=False)),
                ("reviewed_items", models.PositiveIntegerField(default=0, editable=False)),
                ("error_items", models.PositiveIntegerField(default=0, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_consumable_stock_migration_batches", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Lote de conciliación de consumibles", "verbose_name_plural": "Lotes de conciliación de consumibles", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ConsumableStockMigrationItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("printing_reference_snapshot", models.CharField(max_length=100)),
                ("printing_name_snapshot", models.CharField(max_length=200)),
                ("printing_active_snapshot", models.BooleanField()),
                ("printing_initial_stock_snapshot", models.IntegerField()),
                ("printing_entries_snapshot", models.IntegerField()),
                ("printing_outputs_snapshot", models.IntegerField()),
                ("printing_transfers_snapshot", models.IntegerField()),
                ("printing_current_stock_snapshot", models.IntegerField()),
                ("inventory_total_stock_snapshot", models.IntegerField(blank=True, null=True)),
                ("inventory_has_balance_snapshot", models.BooleanField(default=False)),
                ("stock_product_active_snapshot", models.BooleanField(blank=True, null=True)),
                ("match_status", models.CharField(choices=[("LINKED", "Producto vinculado"), ("EXACT_CODE_MATCH", "Coincidencia exacta de código"), ("AMBIGUOUS_CODE", "Código ambiguo"), ("NO_MATCH", "Sin coincidencia")], max_length=30)),
                ("quantity_status", models.CharField(choices=[("MATCH", "Cantidades iguales"), ("PRINTING_GREATER", "Printing mayor"), ("INVENTORY_GREATER", "Inventory mayor"), ("NO_PRODUCT", "Sin producto resuelto"), ("NO_BALANCE", "Inventory sin saldo"), ("NEGATIVE_PRINTING_STOCK", "Stock Printing negativo")], max_length=30)),
                ("decision_status", models.CharField(choices=[("PENDING", "Pendiente"), ("USE_INVENTORY", "Usar Inventory"), ("USE_PRINTING", "Usar Printing"), ("PHYSICAL_COUNT_REQUIRED", "Requiere conteo físico"), ("LINK_EXISTING_PRODUCT", "Vincular producto existente"), ("CREATE_NEW_PRODUCT_LATER", "Crear producto posteriormente"), ("IGNORE_INACTIVE", "Ignorar inactivo"), ("BLOCKED", "Bloqueado")], default="PENDING", max_length=30)),
                ("difference", models.IntegerField(blank=True, null=True)),
                ("approved_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="printing.consumablestockmigrationbatch")),
                ("consumable", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_migration_items", to="printing.consumable")),
                ("destination_branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="consumable_stock_migration_items", to="accounts.branch")),
                ("destination_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="consumable_stock_migration_items", to="inventory.organizationallocation")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_consumable_stock_migration_items", to=settings.AUTH_USER_MODEL)),
                ("stock_product_candidate", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="printing_stock_migration_candidates", to="inventory.stockproduct")),
            ],
            options={
                "verbose_name": "Ítem de conciliación de consumible",
                "verbose_name_plural": "Ítems de conciliación de consumibles",
                "ordering": ["printing_name_snapshot", "printing_reference_snapshot"],
                "constraints": [models.UniqueConstraint(fields=("batch", "consumable"), name="unique_consumable_per_stock_migration_batch")],
            },
        ),
    ]
