# Generated by Django 6.0.7 on 2026-08-19 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_localize_standard_permission_names"),
        ("printing", "0011_consumablestockmigrationbatch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consumablestockmigrationitem",
            name="consolidated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="consumablestockmigrationitem",
            name="consolidated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consolidated_consumable_stock_migration_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consumablestockmigrationitem",
            name="consolidated_quantity",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="consumablestockmigrationitem",
            name="inventory_stock_movement",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_stock_consolidation_item",
                to="inventory.stockmovement",
            ),
        ),
    ]
