# Generated by Django 6.0.7 on 2026-08-19 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_localize_standard_permission_names'),
        ('printing', '0012_consumablestockmigrationitem_consolidated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingTicketStockUsageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id_snapshot', models.CharField(max_length=36, verbose_name='ID histórico del activo')),
                ('asset_internal_code_snapshot', models.CharField(max_length=50, verbose_name='Código interno histórico')),
                ('asset_brand_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Marca histórica')),
                ('asset_model_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Modelo histórico')),
                ('asset_serial_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Serie histórica')),
                ('branch_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Sede histórica')),
                ('location_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Ubicación histórica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_printing_ticket_stock_contexts', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('printing_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_stock_usage_contexts', to='printing.printingdevice', verbose_name='Equipo de impresión')),
                ('usage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='printing_context', to='inventory.ticketstockusage', verbose_name='Consumo de stock')),
            ],
            options={
                'verbose_name': 'Contexto Printing de consumo por ticket',
                'verbose_name_plural': 'Contextos Printing de consumos por ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintingTicketStockUsageLineContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_snapshot', models.CharField(max_length=100, verbose_name='Referencia histórica')),
                ('type_snapshot', models.CharField(max_length=50, verbose_name='Tipo histórico')),
                ('manufacturer_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Fabricante histórico')),
                ('model_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Modelo histórico')),
                ('color_snapshot', models.CharField(blank=True, max_length=50, verbose_name='Color histórico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_stock_usage_line_contexts', to='printing.consumable', verbose_name='Consumible')),
                ('usage_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='printing_context', to='inventory.ticketstockusageline', verbose_name='Línea de consumo')),
            ],
            options={
                'verbose_name': 'Contexto Printing de línea de consumo',
                'verbose_name_plural': 'Contextos Printing de líneas de consumo',
                'ordering': ['created_at'],
            },
        ),
    ]
