# Generated by Django 6.0.7 on 2026-08-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_technicianavailabilityrequest'),
        ('inventory', '0013_localize_standard_permission_names'),
        ('printing', '0013_printingticketstockusagecontext_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printingdevice',
            options={'ordering': ['brand', 'model', 'serial_number'], 'verbose_name': 'Equipo de impresión', 'verbose_name_plural': 'Equipos de impresión'},
        ),
        migrations.AddField(
            model_name='printingdevice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_devices', to='accounts.branch', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='printingdevice',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='printingdevice',
            name='is_outsourced',
            field=models.BooleanField(default=True, verbose_name='Equipo tercerizado'),
        ),
        migrations.AddField(
            model_name='printingdevice',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='printingdevice',
            name='organizational_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_devices', to='inventory.organizationallocation', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='printingdevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='printingdevice',
            name='asset',
            field=models.OneToOneField(blank=True, help_text='Solo para equipos institucionales históricos; no crear activos para equipos tercerizados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printing_device', to='inventory.asset', verbose_name='Activo patrimonial (opcional)'),
        ),
    ]
