# Generated by Django 6.0.7 on 2026-08-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0015_rename_printing_usage_device_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingdevice',
            name='photocopier_id',
            field=models.CharField(blank=True, help_text='Identificador operativo asignado al equipo tercerizado.', max_length=50, null=True, unique=True, verbose_name='ID de fotocopiadora'),
        ),
    ]
