# Generated by Django 6.0.7 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0016_printingdevice_photocopier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP actual'),
        ),
    ]
