# Generated by Django 6.0.7 on 2026-10-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0017_printingdevice_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingdevice',
            name='responsible_identity',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
