# Generated by Django 6.0.7 on 2026-07-12 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código único de la sede. Ejemplo: PLANTA-01.', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('branch_type', models.CharField(choices=[('HEADQUARTERS', 'Casa central'), ('BRANCH', 'Sucursal'), ('INDUSTRIAL_PLANT', 'Planta industrial'), ('OFFICE', 'Oficina administrativa'), ('OTHER', 'Otra')], default='INDUSTRIAL_PLANT', max_length=30, verbose_name='Tipo de sede')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sede activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Sede o planta',
                'verbose_name_plural': 'Sedes y plantas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_email',
            field=models.EmailField(blank=True, help_text='Útil para tercerizados, pasantes o usuarios sin correo corporativo.', max_length=254, null=True, verbose_name='Correo alternativo'),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('SUSPENDED', 'Suspendido')], default='APPROVED', help_text='Los usuarios existentes quedan aprobados para no bloquear su acceso.', max_length=20, verbose_name='Estado de aprobación'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de funcionario'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_end_date',
            field=models.DateField(blank=True, help_text='Especialmente útil para pasantes, tercerizados y contratados.', null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Funcionario permanente'), ('CONTRACTED', 'Funcionario contratado'), ('OUTSOURCED', 'Tercerizado'), ('INTERN', 'Pasante'), ('CONSULTANT', 'Consultor'), ('EXTERNAL_PROVIDER', 'Proveedor externo'), ('OTHER', 'Otro')], default='PERMANENT', max_length=30, verbose_name='Tipo de vínculo'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_company',
            field=models.CharField(blank=True, help_text='Empresa del tercerizado, consultor o proveedor externo.', max_length=150, null=True, verbose_name='Empresa de origen'),
        ),
        migrations.AddField(
            model_name='user',
            name='internal_responsible',
            field=models.ForeignKey(blank=True, help_text='Funcionario interno responsable del tercerizado, pasante o proveedor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_users_under_responsibility', to=settings.AUTH_USER_MODEL, verbose_name='Responsable interno'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_temporary_account',
            field=models.BooleanField(default=False, verbose_name='Cuenta temporal'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar la contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('TECHNICIAN', 'Técnico'), ('AUDITOR', 'Auditor'), ('CLIENT', 'Usuario final')], default='CLIENT', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.branch', verbose_name='Sede o planta'),
        ),
    ]
