# Generated by Django 6.0.7 on 2026-08-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_auto_assignment_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última asignación automática'),
        ),
    ]
