# Generated by Django 6.0.7 on 2026-08-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_auto_assignment_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BUSY', 'Ocupado'), ('UNAVAILABLE', 'No disponible')], default='AVAILABLE', max_length=20, verbose_name='Disponibilidad'),
        ),
    ]
