# Generated by Django 6.0.7 on 2026-08-09 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_availability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del turno')),
                ('start_time', models.TimeField(verbose_name='Hora de entrada')),
                ('end_time', models.TimeField(verbose_name='Hora de salida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Turno laboral',
                'verbose_name_plural': 'Turnos laborales',
                'ordering': ['start_time', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianWorkday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('started_at', models.DateTimeField(verbose_name='Inicio real de jornada')),
                ('scheduled_end_at', models.DateTimeField(verbose_name='Fin programado de jornada')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin real de jornada')),
                ('status', models.CharField(choices=[('ACTIVE', 'Presente'), ('FINISHED', 'Finalizada')], default='ACTIVE', max_length=20, verbose_name='Estado de jornada')),
                ('ended_automatically', models.BooleanField(default=False, verbose_name='Finalizada automáticamente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_workdays', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_workdays', to='accounts.workshift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Jornada de técnico',
                'verbose_name_plural': 'Jornadas de técnicos',
                'ordering': ['-date', '-started_at'],
                'constraints': [models.UniqueConstraint(fields=('technician', 'date'), name='unique_technician_workday_per_date')],
            },
        ),
    ]
