# Generated by Django 6.0.7 on 2026-08-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workshift_technicianworkday'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='technicianworkday',
            name='unique_technician_workday_per_date',
        ),
    ]
