# Generated by Django 6.0.7 on 2026-08-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_technicianavailabilityrequest'),
        ('core', '0006_localize_standard_permission_names'),
        ('institution', '0003_organizationalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, help_text='Dependencia real del funcionario dentro del organigrama institucional: Dirección, Gerencia, Unidad, Departamento, Oficina u otra dependencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='institution.organizationalunit', verbose_name='Dependencia institucional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Departamento utilizado internamente por NovaDesk Pro para tickets, categorías, SLA y asignaciones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.department', verbose_name='Departamento operativo'),
        ),
    ]
