# Generated by Django 6.0.7 on 2026-10-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_technicianavailabilityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_personal',
            field=models.PositiveIntegerField(blank=True, help_text='Identificador único del funcionario en la fuente institucional de RR.HH.', null=True, unique=True, verbose_name='IdPersonal RR.HH.'),
        ),
    ]
