# Generated by Django 6.0.7 on 2026-07-18 00:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_asset_branch_alter_asset_assigned_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('logged_user', models.CharField(blank=True, max_length=150, verbose_name='Usuario conectado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP actual')),
                ('mac_address', models.CharField(blank=True, max_length=50, verbose_name='Dirección MAC')),
                ('operating_system', models.CharField(blank=True, max_length=200, verbose_name='Sistema operativo')),
                ('processor', models.CharField(blank=True, max_length=250, verbose_name='Procesador')),
                ('ram_total_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Memoria RAM total (GB)')),
                ('disk_total_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Disco total (GB)')),
                ('disk_free_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Disco disponible (GB)')),
                ('agent_version', models.CharField(blank=True, max_length=50, verbose_name='Versión del agente')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última comunicación')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Primera comunicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_heartbeat', to='inventory.asset', verbose_name='Activo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_device_heartbeats', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Estado de equipo',
                'verbose_name_plural': 'Estados de equipos',
                'ordering': ['computer_name'],
            },
        ),
    ]
