# Generated by Django 6.0.7 on 2026-07-18 03:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('computer_name', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('logged_user', models.CharField(blank=True, max_length=150, verbose_name='Usuario conectado')),
                ('mac_address', models.CharField(blank=True, max_length=50, verbose_name='Dirección MAC')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Primera detección')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última detección')),
                ('detection_count', models.PositiveIntegerField(default=1, verbose_name='Cantidad de detecciones')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_history', to='monitoring.deviceheartbeat', verbose_name='Equipo monitoreado')),
            ],
            options={
                'verbose_name': 'Historial de IP',
                'verbose_name_plural': 'Historial de IP',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['ip_address'], name='monitoring__ip_addr_099f7a_idx'), models.Index(fields=['-last_seen'], name='monitoring__last_se_0086a9_idx')],
            },
        ),
    ]
