from django.urls import path

from .import_views import (
    asset_import_template_view,
    asset_import_view,
)
from .views import (
    asset_create_view,
    asset_detail_view,
    asset_list_view,
    asset_update_view,
    technical_history_create_view,
    my_asset_list,  # ✅ YA ESTÁ IMPORTADO
    stock_category_create_view,
    stock_category_list_view,
    stock_category_update_view,
    stock_entry_view,
    stock_exit_view,
    stock_movement_list_view,
    stock_product_create_view,
    stock_product_detail_view,
    stock_product_list_view,
    stock_product_update_view,
    stock_transfer_view,
    documented_stock_entry_list_view,
    documented_stock_entry_create_view,
    documented_stock_entry_detail_view,
    documented_stock_entry_update_view,
    documented_stock_entry_add_line_view,
    documented_stock_entry_delete_line_view,
    documented_stock_entry_add_document_view,
    documented_stock_entry_document_download_view,
    documented_stock_entry_confirm_view,
    documented_stock_entry_cancel_view,
    stock_delivery_list_view,
    stock_delivery_create_view,
    stock_delivery_detail_view,
    stock_delivery_update_view,
    stock_delivery_add_line_view,
    stock_delivery_delete_line_view,
    stock_delivery_prepare_view,
    stock_delivery_complete_view,
    stock_delivery_cancel_view,
    stock_delivery_pdf_view,
    stock_delivery_signed_document_upload_view,
    stock_delivery_signed_document_download_view,
    ticket_stock_usage_list_view,
    ticket_stock_usage_create_view,
    ticket_stock_usage_detail_view,
    ticket_stock_usage_update_view,
    ticket_stock_usage_add_line_view,
    ticket_stock_usage_delete_line_view,
    ticket_stock_usage_confirm_view,
    ticket_stock_usage_cancel_view,
)


app_name = "inventory"


urlpatterns = [
    path("stock/consumos-tickets/", ticket_stock_usage_list_view, name="ticket_stock_usage_list"),
    path("stock/consumos-tickets/nuevo/", ticket_stock_usage_create_view, name="ticket_stock_usage_create"),
    path("stock/consumos-tickets/<uuid:pk>/", ticket_stock_usage_detail_view, name="ticket_stock_usage_detail"),
    path("stock/consumos-tickets/<uuid:pk>/editar/", ticket_stock_usage_update_view, name="ticket_stock_usage_update"),
    path("stock/consumos-tickets/<uuid:pk>/lineas/agregar/", ticket_stock_usage_add_line_view, name="ticket_stock_usage_add_line"),
    path("stock/consumos-tickets/<uuid:pk>/lineas/<uuid:line_pk>/eliminar/", ticket_stock_usage_delete_line_view, name="ticket_stock_usage_delete_line"),
    path("stock/consumos-tickets/<uuid:pk>/confirmar/", ticket_stock_usage_confirm_view, name="ticket_stock_usage_confirm"),
    path("stock/consumos-tickets/<uuid:pk>/cancelar/", ticket_stock_usage_cancel_view, name="ticket_stock_usage_cancel"),
    path("stock/entregas/", stock_delivery_list_view, name="stock_delivery_list"),
    path("stock/entregas/nueva/", stock_delivery_create_view, name="stock_delivery_create"),
    path("stock/entregas/<uuid:pk>/", stock_delivery_detail_view, name="stock_delivery_detail"),
    path("stock/entregas/<uuid:pk>/editar/", stock_delivery_update_view, name="stock_delivery_update"),
    path("stock/entregas/<uuid:pk>/lineas/agregar/", stock_delivery_add_line_view, name="stock_delivery_add_line"),
    path("stock/entregas/<uuid:pk>/lineas/<uuid:line_pk>/eliminar/", stock_delivery_delete_line_view, name="stock_delivery_delete_line"),
    path("stock/entregas/<uuid:pk>/preparar/", stock_delivery_prepare_view, name="stock_delivery_prepare"),
    path("stock/entregas/<uuid:pk>/completar/", stock_delivery_complete_view, name="stock_delivery_complete"),
    path("stock/entregas/<uuid:pk>/cancelar/", stock_delivery_cancel_view, name="stock_delivery_cancel"),
    path("stock/entregas/<uuid:pk>/acta.pdf", stock_delivery_pdf_view, name="stock_delivery_pdf"),
    path("stock/entregas/<uuid:pk>/acta-firmada/subir/", stock_delivery_signed_document_upload_view, name="stock_delivery_signed_upload"),
    path("stock/entregas/<uuid:pk>/acta-firmada/descargar/", stock_delivery_signed_document_download_view, name="stock_delivery_signed_download"),
    path("stock/entradas-documentadas/", documented_stock_entry_list_view, name="documented_stock_entry_list"),
    path("stock/entradas-documentadas/nueva/", documented_stock_entry_create_view, name="documented_stock_entry_create"),
    path("stock/entradas-documentadas/<uuid:pk>/", documented_stock_entry_detail_view, name="documented_stock_entry_detail"),
    path("stock/entradas-documentadas/<uuid:pk>/editar/", documented_stock_entry_update_view, name="documented_stock_entry_update"),
    path("stock/entradas-documentadas/<uuid:pk>/lineas/agregar/", documented_stock_entry_add_line_view, name="documented_stock_entry_add_line"),
    path("stock/entradas-documentadas/<uuid:pk>/lineas/<uuid:line_pk>/eliminar/", documented_stock_entry_delete_line_view, name="documented_stock_entry_delete_line"),
    path("stock/entradas-documentadas/<uuid:pk>/documentos/agregar/", documented_stock_entry_add_document_view, name="documented_stock_entry_add_document"),
    path("stock/entradas-documentadas/<uuid:pk>/documentos/<uuid:document_pk>/descargar/", documented_stock_entry_document_download_view, name="documented_stock_entry_document_download"),
    path("stock/entradas-documentadas/<uuid:pk>/confirmar/", documented_stock_entry_confirm_view, name="documented_stock_entry_confirm"),
    path("stock/entradas-documentadas/<uuid:pk>/cancelar/", documented_stock_entry_cancel_view, name="documented_stock_entry_cancel"),
    path("stock/", stock_product_list_view, name="stock_product_list"),
    path("stock/productos/nuevo/", stock_product_create_view, name="stock_product_create"),
    path("stock/productos/<uuid:pk>/", stock_product_detail_view, name="stock_product_detail"),
    path("stock/productos/<uuid:pk>/editar/", stock_product_update_view, name="stock_product_update"),
    path("stock/categorias/", stock_category_list_view, name="stock_category_list"),
    path("stock/categorias/nueva/", stock_category_create_view, name="stock_category_create"),
    path("stock/categorias/<uuid:pk>/editar/", stock_category_update_view, name="stock_category_update"),
    path("stock/entrada/", stock_entry_view, name="stock_entry"),
    path("stock/salida/", stock_exit_view, name="stock_exit"),
    path("stock/transferencia/", stock_transfer_view, name="stock_transfer"),
    path("stock/movimientos/", stock_movement_list_view, name="stock_movement_list"),
    path(
        "",
        asset_list_view,
        name="asset_list",
    ),
    path('my-assets/', my_asset_list, name='my_asset_list'),  # ✅ CORREGIDO (sin views.)

    path(
        "nuevo/",
        asset_create_view,
        name="asset_create",
    ),
    path(
        "importar/",
        asset_import_view,
        name="asset_import",
    ),
    path(
        "importar/plantilla/",
        asset_import_template_view,
        name="asset_import_template",
    ),
    path(
        "<uuid:pk>/",
        asset_detail_view,
        name="asset_detail",
    ),
    path(
        "<uuid:pk>/editar/",
        asset_update_view,
        name="asset_update",
    ),
    path(
        "<uuid:asset_pk>/intervenciones/nueva/",
        technical_history_create_view,
        name="technical_history_create",
    ),
    
]
