# Generated by Django 6.0.7 on 2026-07-12 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('assign', 'Asignación'), ('status', 'Cambio de estado'), ('comment', 'Comentario'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('other', 'Otra acción')], default='other', max_length=30, verbose_name='Acción')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Módulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de objeto')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-created_at'],
            },
        ),
    ]
