# Generated by Django 6.0.7 on 2026-07-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del objeto'),
        ),
    ]
