# Generated by Django 6.0.7 on 2026-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activitylog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('assign', 'Asignación'), ('status', 'Cambio de estado'), ('comment', 'Comentario'), ('attachment', 'Archivo adjunto'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('other', 'Otra acción')], default='other', max_length=30, verbose_name='Acción'),
        ),
    ]
