# Generated by Django 6.0.7 on 2026-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('assign', 'Asignación'), ('status', 'Cambio de estado'), ('comment', 'Comentario'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('other', 'Otra acción')], default='other', max_length=30, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del objeto'),
        ),
    ]
