# Generated by Django 6.0.7 on 2026-07-11 15:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_alter_assettechnicalhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCustodyMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número de movimiento')),
                ('movement_type', models.CharField(choices=[('DELIVERY', 'Entrega'), ('RETURN', 'Devolución'), ('REASSIGNMENT', 'Reasignación'), ('RESERVATION', 'Reserva'), ('CANCELLATION', 'Cancelación')], default='DELIVERY', max_length=20, verbose_name='Tipo de movimiento')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_SIGNATURES', 'Pendiente de firmas'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=25, verbose_name='Estado del movimiento')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departamento de destino')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación de destino')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del movimiento')),
                ('accessories', models.TextField(blank=True, verbose_name='Accesorios entregados')),
                ('asset_condition', models.TextField(blank=True, verbose_name='Estado físico del equipo')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('director_signature', models.ImageField(blank=True, null=True, upload_to='deliveries/signatures/director/%Y/%m/', verbose_name='Firma del director')),
                ('responsible_signature', models.ImageField(blank=True, null=True, upload_to='deliveries/signatures/responsible/%Y/%m/', verbose_name='Firma del responsable')),
                ('recipient_signature', models.ImageField(blank=True, null=True, upload_to='deliveries/signatures/recipient/%Y/%m/', verbose_name='Firma del receptor')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='deliveries/documents/%Y/%m/', verbose_name='Acta firmada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_movements', to='inventory.asset', verbose_name='Activo')),
                ('authorizing_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_movements_authorized', to=settings.AUTH_USER_MODEL, verbose_name='Director que autoriza')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_custody_movements', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('delivery_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_movements_delivered', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de entrega')),
                ('previous_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_movements_released', to=settings.AUTH_USER_MODEL, verbose_name='Custodio anterior')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_movements_received', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Movimiento de custodia',
                'verbose_name_plural': 'Movimientos de custodia',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
