# Generated by Django 6.0.7 on 2026-07-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcustodymovement',
            name='status',
            field=models.CharField(choices=[('IN_DELIVERY_PROCESS', 'En proceso de entrega')], default='IN_DELIVERY_PROCESS', max_length=25, verbose_name='Estado del movimiento'),
        ),
    ]
