# Generated by Django 6.0.7 on 2026-07-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_assetcustodymovement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_employee_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Legajo del receptor'),
        ),
    ]
