# Generated by Django 6.0.7 on 2026-07-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_assetcustodymovement_recipient_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cargo del receptor'),
        ),
    ]
