# Generated by Django 6.0.7 on 2026-07-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_assetcustodymovement_recipient_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_area',
            field=models.CharField(blank=True, max_length=120, verbose_name='Área del receptor'),
        ),
    ]
