# Generated by Django 6.0.7 on 2026-07-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_assetcustodymovement_recipient_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_unit',
            field=models.CharField(blank=True, max_length=120, verbose_name='Unidad del receptor'),
        ),
    ]
