# Generated by Django 6.0.7 on 2026-07-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_assetcustodymovement_recipient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_section',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sección del receptor'),
        ),
    ]
