# Generated by Django 6.0.7 on 2026-07-26 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_assetcustodymovement_recipient_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('DELIVERY_FORM', 'Hoja de entrega firmada'), ('PATRIMONIAL_FORM', 'Hoja patrimonial firmada'), ('OTHER', 'Otro documento')], max_length=30, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to='deliveries/audit_documents/%Y/%m/', verbose_name='Archivo')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_documents', to='deliveries.assetcustodymovement', verbose_name='Movimiento de entrega')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_delivery_documents', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Documento de entrega',
                'verbose_name_plural': 'Documentos de entrega',
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_type__in', ['DELIVERY_FORM', 'PATRIMONIAL_FORM'])), fields=('movement', 'document_type'), name='unique_required_document_per_movement')],
            },
        ),
    ]
