# Generated by Django 6.0.7 on 2026-07-26 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_deliverydocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número de acta agrupada')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PREPARED', 'Preparado'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=25, verbose_name='Estado del acta')),
                ('recipient_employee_number', models.CharField(blank=True, max_length=30, verbose_name='Legajo del receptor')),
                ('recipient_position', models.CharField(blank=True, max_length=120, verbose_name='Cargo del receptor')),
                ('recipient_area', models.CharField(blank=True, max_length=120, verbose_name='Área del receptor')),
                ('recipient_unit', models.CharField(blank=True, max_length=120, verbose_name='Unidad del receptor')),
                ('recipient_section', models.CharField(blank=True, max_length=120, verbose_name='Sección del receptor')),
                ('origin_unit', models.CharField(blank=True, max_length=120, verbose_name='Unidad de origen')),
                ('origin_department', models.CharField(blank=True, max_length=120, verbose_name='Departamento de origen')),
                ('origin_area', models.CharField(blank=True, max_length=120, verbose_name='Área de origen')),
                ('origin_section', models.CharField(blank=True, max_length=120, verbose_name='Sección de origen')),
                ('origin_position', models.CharField(blank=True, max_length=120, verbose_name='Cargo del responsable de origen')),
                ('origin_employee_number', models.CharField(blank=True, max_length=30, verbose_name='Legajo del responsable de origen')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departamento de destino')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación de destino')),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de entrega')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('director_signature', models.ImageField(blank=True, null=True, upload_to='deliveries/batches/signatures/director/%Y/%m/', verbose_name='Firma del director')),
                ('responsible_signature', models.ImageField(blank=True, null=True, upload_to='deliveries/batches/signatures/responsible/%Y/%m/', verbose_name='Firma del responsable')),
                ('recipient_signature', models.ImageField(blank=True, null=True, upload_to='deliveries/batches/signatures/recipient/%Y/%m/', verbose_name='Firma del receptor')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='deliveries/batches/documents/%Y/%m/', verbose_name='Acta agrupada firmada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('authorizing_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_batches_authorized', to=settings.AUTH_USER_MODEL, verbose_name='Director que autoriza')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_batches', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('delivery_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_batches_delivered', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de entrega')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_batches_received', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Acta agrupada de entrega',
                'verbose_name_plural': 'Actas agrupadas de entrega',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assetcustodymovement',
            name='delivery_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='deliveries.deliverybatch', verbose_name='Acta agrupada'),
        ),
    ]
