# Generated by Django 6.0.7 on 2026-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_localize_delivery_permission_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_id_personal',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='IdPersonal del receptor'),
        ),
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del receptor'),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='recipient_id_personal',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='IdPersonal del receptor'),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del receptor'),
        ),
    ]
