# Generated by Django 6.0.7 on 2026-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_assetcustodymovement_recipient_id_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del receptor'),
        ),
        migrations.AddField(
            model_name='assetcustodymovement',
            name='recipient_source',
            field=models.CharField(blank=True, max_length=30, verbose_name='Fuente institucional del receptor'),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del receptor'),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='recipient_source',
            field=models.CharField(blank=True, max_length=30, verbose_name='Fuente institucional del receptor'),
        ),
    ]
