# Generated by Django 6.0.7 on 2026-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Petróleos Paraguayos', max_length=180, verbose_name='Nombre de la institución')),
                ('institution_short_name', models.CharField(blank=True, default='PETROPAR', max_length=80, verbose_name='Nombre corto')),
                ('department_name', models.CharField(blank=True, default='Dirección de Tecnología de la Información', max_length=180, verbose_name='Departamento o dependencia')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='institution/header/', verbose_name='Imagen de encabezado')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/logo/', verbose_name='Logotipo')),
                ('address', models.CharField(blank=True, max_length=220, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, default='Villa Elisa', max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, default='Paraguay', max_length=100, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo institucional')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('director_name', models.CharField(blank=True, max_length=160, verbose_name='Director responsable')),
                ('document_code', models.CharField(blank=True, default='TI-ACT-001', max_length=50, verbose_name='Código del documento')),
                ('primary_color', models.CharField(default='#1E40AF', help_text='Formato hexadecimal, por ejemplo: #1E40AF', max_length=7, verbose_name='Color institucional principal')),
                ('secondary_color', models.CharField(default='#0F172A', help_text='Formato hexadecimal, por ejemplo: #0F172A', max_length=7, verbose_name='Color institucional secundario')),
                ('footer_text', models.CharField(blank=True, default='Documento generado automáticamente por NovaDesk Pro.', max_length=255, verbose_name='Texto de pie de página')),
                ('is_active', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración institucional',
                'verbose_name_plural': 'Configuración institucional',
            },
        ),
    ]
