# Generated by Django 6.0.7 on 2026-07-12 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionsettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Configuración del sistema', 'verbose_name_plural': 'Configuración del sistema'},
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='accent_color',
            field=models.CharField(default='#38BDF8', help_text='Se utiliza en enlaces, indicadores y elementos destacados.', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido. Ejemplo: #1E40AF.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de acento'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='admin_logo',
            field=models.ImageField(blank=True, help_text='Si queda vacío, se utilizará el logo principal.', null=True, upload_to='institution/admin/', verbose_name='Logo del panel de administración'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='allow_user_theme_change',
            field=models.BooleanField(default=True, verbose_name='Permitir que cada usuario cambie el tema'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='compact_logo',
            field=models.ImageField(blank=True, help_text='Versión reducida para el menú lateral, navbar o dispositivos móviles.', null=True, upload_to='institution/logo/compact/', verbose_name='Logo compacto'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='currency_code',
            field=models.CharField(default='PYG', help_text='Ejemplos: PYG, USD o BRL.', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='danger_color',
            field=models.CharField(default='#DC2626', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido. Ejemplo: #1E40AF.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de error o peligro'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='dark_logo',
            field=models.ImageField(blank=True, help_text='Versión clara o blanca del logo para fondos oscuros.', null=True, upload_to='institution/logo/dark/', verbose_name='Logo para modo oscuro'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='dashboard_image',
            field=models.ImageField(blank=True, help_text='Imagen opcional para la portada o encabezado del dashboard.', null=True, upload_to='institution/dashboard/', verbose_name='Imagen del dashboard'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='date_format',
            field=models.CharField(default='d/m/Y', help_text='Formato de Django. Ejemplo: d/m/Y.', max_length=30, verbose_name='Formato de fecha'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='default_theme',
            field=models.CharField(choices=[('LIGHT', 'Claro'), ('DARK', 'Oscuro'), ('SYSTEM', 'Automático según el dispositivo')], default='LIGHT', max_length=10, verbose_name='Tema predeterminado'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Se recomienda una imagen cuadrada, por ejemplo 32 × 32 o 64 × 64 píxeles.', null=True, upload_to='institution/favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Icono del navegador'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='login_image',
            field=models.ImageField(blank=True, help_text='Imagen principal o fondo de la pantalla de inicio de sesión.', null=True, upload_to='institution/login/', verbose_name='Imagen de inicio de sesión'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='monitoring_logo',
            field=models.ImageField(blank=True, help_text='Logo específico para pantallas de monitoreo.', null=True, upload_to='institution/monitoring/', verbose_name='Logo de monitoreo'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='show_header_in_pdf',
            field=models.BooleanField(default=True, verbose_name='Mostrar encabezado institucional en PDF'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='show_logo_in_pdf',
            field=models.BooleanField(default=True, verbose_name='Mostrar logo en documentos PDF'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='success_color',
            field=models.CharField(default='#16A34A', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido. Ejemplo: #1E40AF.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de éxito'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='system_name',
            field=models.CharField(default='NovaDesk Pro', max_length=120, verbose_name='Nombre del sistema'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='system_short_name',
            field=models.CharField(blank=True, default='NovaDesk', max_length=50, verbose_name='Nombre corto del sistema'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='system_slogan',
            field=models.CharField(blank=True, default='Gestión integral de soporte e infraestructura tecnológica', max_length=220, verbose_name='Eslogan del sistema'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='timezone_name',
            field=models.CharField(default='America/Asuncion', max_length=60, verbose_name='Zona horaria'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='user_portal_logo',
            field=models.ImageField(blank=True, help_text='Si queda vacío, se utilizará el logo principal.', null=True, upload_to='institution/portal/', verbose_name='Logo del portal de usuarios'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='warning_color',
            field=models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido. Ejemplo: #1E40AF.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de advertencia'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Encabezado utilizado en actas, reportes y PDF.', null=True, upload_to='institution/header/', verbose_name='Imagen de encabezado para documentos'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='institution_short_name',
            field=models.CharField(blank=True, default='PETROPAR', max_length=80, verbose_name='Nombre corto de la institución'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo utilizado normalmente en fondos claros.', null=True, upload_to='institution/logo/', verbose_name='Logo principal'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='primary_color',
            field=models.CharField(default='#1E40AF', help_text='Formato hexadecimal. Ejemplo: #1E40AF.', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido. Ejemplo: #1E40AF.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color principal'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='secondary_color',
            field=models.CharField(default='#0F172A', help_text='Formato hexadecimal. Ejemplo: #0F172A.', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido. Ejemplo: #1E40AF.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color secundario'),
        ),
    ]
