# Generated by Django 6.0.7 on 2026-08-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_localize_standard_permission_names'),
        ('institution', '0002_alter_institutionsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Código')),
                ('unit_type', models.CharField(choices=[('PRESIDENCY', 'Presidencia'), ('GENERAL_MANAGEMENT', 'Gerencia General'), ('MANAGEMENT', 'Gerencia'), ('DIRECTORATE', 'Dirección'), ('DEPUTY_DIRECTORATE', 'Dirección Adjunta'), ('SUB_MANAGEMENT', 'Sub-Gerencia'), ('UNIT', 'Unidad'), ('OFFICE', 'Oficina'), ('DEPARTMENT', 'Departamento'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de dependencia')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('operational_department', models.ForeignKey(blank=True, help_text='Relación opcional con un departamento operativo utilizado por tickets, usuarios e inventario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizational_units', to='core.department', verbose_name='Departamento operativo relacionado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='institution.organizationalunit', verbose_name='Dependencia superior')),
            ],
            options={
                'verbose_name': 'Dependencia institucional',
                'verbose_name_plural': 'Dependencias institucionales',
                'ordering': ['parent_id', 'order', 'name'],
            },
        ),
    ]
