# Generated by Django 6.0.7 on 2026-10-03 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_organizationalunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalIdentityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personal', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='IdPersonal RR.HH.')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Correo institucional')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Usuario de red')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_assignments', to='institution.organizationalunit', verbose_name='Dependencia institucional')),
            ],
            options={
                'verbose_name': 'Asignación institucional',
                'verbose_name_plural': 'Asignaciones institucionales',
                'ordering': ['organizational_unit__name', 'email', 'username'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_personal__isnull', False)), fields=('id_personal',), name='unique_institutional_assignment_id_personal'), models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_institutional_assignment_email'), models.UniqueConstraint(condition=models.Q(('username', ''), _negated=True), fields=('username',), name='unique_institutional_assignment_username'), models.CheckConstraint(condition=models.Q(('id_personal__isnull', False), models.Q(('email', ''), _negated=True), models.Q(('username', ''), _negated=True), _connector='OR'), name='institutional_assignment_requires_identifier')],
            },
        ),
    ]
