# Generated by Django 6.0.7 on 2026-07-10 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_code', models.CharField(max_length=50, unique=True, verbose_name='Código interno')),
                ('patrimonial_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código patrimonial')),
                ('asset_type', models.CharField(choices=[('DESKTOP', 'Computadora de escritorio'), ('LAPTOP', 'Notebook'), ('PRINTER', 'Impresora'), ('SCANNER', 'Escáner'), ('MONITOR', 'Monitor'), ('UPS', 'UPS'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('IP_PHONE', 'Teléfono IP'), ('OTHER', 'Otro')], default='DESKTOP', max_length=20, verbose_name='Tipo de equipo')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Número de serie')),
                ('hostname', models.CharField(blank=True, max_length=150, verbose_name='Nombre del equipo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación')),
                ('operational_status', models.CharField(choices=[('OPERATIONAL', 'Operativo'), ('MAINTENANCE', 'En mantenimiento'), ('OBSERVATION', 'En observación'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('RETIRED', 'Dado de baja')], default='OPERATIONAL', max_length=30, verbose_name='Estado operativo')),
                ('connection_status', models.CharField(choices=[('ONLINE', 'En línea'), ('OFFLINE', 'Fuera de línea'), ('UNKNOWN', 'Sin información')], default='UNKNOWN', max_length=20, verbose_name='Estado de conexión')),
                ('operating_system', models.CharField(blank=True, max_length=150, verbose_name='Sistema operativo')),
                ('current_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Dirección IP actual')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Dirección MAC')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('warranty_expiration', models.DateField(blank=True, null=True, verbose_name='Vencimiento de garantía')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
            ],
            options={
                'verbose_name': 'Activo informático',
                'verbose_name_plural': 'Activos informáticos',
                'ordering': ['internal_code'],
            },
        ),
    ]
