# Generated by Django 6.0.7 on 2026-07-11 12:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tickets', '0006_ticket_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTechnicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intervention_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnóstico'), ('REPAIR', 'Reparación'), ('PREVENTIVE_MAINTENANCE', 'Mantenimiento preventivo'), ('CORRECTIVE_MAINTENANCE', 'Mantenimiento correctivo'), ('COMPONENT_REPLACEMENT', 'Cambio de componente'), ('SOFTWARE_INSTALLATION', 'Instalación de software'), ('OPERATING_SYSTEM', 'Sistema operativo'), ('OTHER', 'Otro')], default='DIAGNOSIS', max_length=40)),
                ('diagnosis', models.TextField(blank=True)),
                ('action_taken', models.TextField()),
                ('components_replaced', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('intervention_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_history', to='inventory.asset', verbose_name='Activo')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsable')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_interventions', to='tickets.ticket', verbose_name='Ticket relacionado')),
            ],
            options={
                'ordering': ['-intervention_date'],
            },
        ),
    ]
