# Generated by Django 6.0.7 on 2026-07-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_assettechnicalhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettechnicalhistory',
            options={'ordering': ['-intervention_date'], 'verbose_name': 'Intervención técnica', 'verbose_name_plural': 'Intervenciones técnicas'},
        ),
    ]
