# Generated by Django 6.0.7 on 2026-07-12 04:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_user_alternative_email_user_approval_status_and_more'),
        ('inventory', '0003_alter_assettechnicalhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sede o planta donde se encuentra físicamente el equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounts.branch', verbose_name='Sede o planta'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='Persona responsable o custodio del equipo. No necesariamente representa su ubicación física.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, help_text='Campo adicional para referencias como mesa, rack, puesto, oficina o sector específico.', max_length=150, verbose_name='Ubicación descriptiva'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='action_taken',
            field=models.TextField(verbose_name='Acción realizada'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='components_replaced',
            field=models.TextField(blank=True, verbose_name='Componentes reemplazados'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en minutos'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='intervention_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de intervención'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='intervention_type',
            field=models.CharField(choices=[('DIAGNOSIS', 'Diagnóstico'), ('REPAIR', 'Reparación'), ('PREVENTIVE_MAINTENANCE', 'Mantenimiento preventivo'), ('CORRECTIVE_MAINTENANCE', 'Mantenimiento correctivo'), ('COMPONENT_REPLACEMENT', 'Cambio de componente'), ('SOFTWARE_INSTALLATION', 'Instalación de software'), ('OPERATING_SYSTEM', 'Sistema operativo'), ('OTHER', 'Otro')], default='DIAGNOSIS', max_length=40, verbose_name='Tipo de intervención'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='assettechnicalhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.CreateModel(
            name='OrganizationalLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código único dentro de la sede. Ejemplo: EDIF-A, PISO-02 u OF-203.', max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('location_type', models.CharField(choices=[('BUILDING', 'Edificio'), ('FLOOR', 'Piso'), ('OFFICE', 'Oficina'), ('AREA', 'Área o sector'), ('WAREHOUSE', 'Depósito'), ('SERVER_ROOM', 'Sala de servidores'), ('WORKSHOP', 'Taller técnico'), ('MEETING_ROOM', 'Sala de reuniones'), ('PRODUCTION_AREA', 'Área de producción'), ('OTHER', 'Otra ubicación')], default='AREA', max_length=30, verbose_name='Tipo de ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ubicación activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizational_locations', to='accounts.branch', verbose_name='Sede o planta')),
                ('parent', models.ForeignKey(blank=True, help_text='Ejemplo: una oficina puede depender de un piso, y un piso puede depender de un edificio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.organizationallocation', verbose_name='Ubicación superior')),
            ],
            options={
                'verbose_name': 'Ubicación organizacional',
                'verbose_name_plural': 'Ubicaciones organizacionales',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='physical_location',
            field=models.ForeignKey(blank=True, help_text='Edificio, piso, oficina, depósito, sala técnica o sector.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.organizationallocation', verbose_name='Ubicación física detallada'),
        ),
        migrations.AddConstraint(
            model_name='organizationallocation',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_organizational_location_code_per_branch'),
        ),
    ]
