# Generated by Django 6.0.7 on 2026-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_asset_branch_alter_asset_assigned_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to='batches/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
