# Generated by Django 6.0.7 on 2026-07-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_acquisitionbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='acquisition_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.acquisitionbatch', verbose_name='Lote de adquisición'),
        ),
    ]
