# Generated by Django 6.0.7 on 2026-08-14 21:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_seed_default_work_shifts"),
        ("core", "0005_businesssequence"),
        ("inventory", "0007_alter_acquisitionbatch_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                ("code", models.SlugField(unique=True, verbose_name="Código")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Última actualización")),
            ],
            options={
                "verbose_name": "Categoría de stock",
                "verbose_name_plural": "Categorías de stock",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockProduct",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("reference_code", models.CharField(max_length=100, unique=True, verbose_name="Código de referencia")),
                ("brand", models.CharField(blank=True, max_length=150, verbose_name="Marca")),
                ("model", models.CharField(blank=True, max_length=150, verbose_name="Modelo")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                ("unit_of_measure", models.CharField(choices=[("UNIT", "Unidad"), ("BOX", "Caja"), ("METER", "Metro"), ("ROLL", "Rollo"), ("PACKAGE", "Paquete")], default="UNIT", max_length=20, verbose_name="Unidad de medida")),
                ("minimum_stock", models.PositiveIntegerField(default=0, verbose_name="Stock mínimo")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Última actualización")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="inventory.stockcategory", verbose_name="Categoría")),
                ("default_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="default_stock_products", to="inventory.organizationallocation", verbose_name="Ubicación predeterminada")),
            ],
            options={
                "verbose_name": "Producto de stock",
                "verbose_name_plural": "Productos de stock",
                "ordering": ["name", "reference_code"],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="Cantidad actual")),
                ("minimum_stock", models.PositiveIntegerField(blank=True, null=True, verbose_name="Stock mínimo en la ubicación")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Última actualización")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="accounts.branch", verbose_name="Sede o planta")),
                ("organizational_location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.organizationallocation", verbose_name="Ubicación organizacional")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="balances", to="inventory.stockproduct", verbose_name="Producto")),
            ],
            options={
                "verbose_name": "Saldo de stock",
                "verbose_name_plural": "Saldos de stock",
                "ordering": ["product__name", "branch__name", "organizational_location__name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(verbose_name="Cantidad")),
                ("direction", models.CharField(choices=[("ENTRY", "Entrada"), ("EXIT", "Salida")], max_length=10, verbose_name="Dirección")),
                ("reason", models.CharField(choices=[("PURCHASE", "Compra"), ("RETURN", "Devolución"), ("DELIVERY", "Entrega"), ("REPAIR", "Uso en reparación"), ("CONSUMPTION", "Consumo"), ("WRITE_OFF", "Baja"), ("ADJUSTMENT", "Ajuste"), ("OTHER", "Otro")], max_length=20, verbose_name="Motivo")),
                ("movement_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Fecha del movimiento")),
                ("observation", models.TextField(blank=True, verbose_name="Observación")),
                ("document_reference", models.CharField(blank=True, max_length=100, verbose_name="Referencia documental")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de registro")),
                ("balance", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.stockbalance", verbose_name="Saldo")),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="core.department", verbose_name="Departamento")),
                ("performed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_stock_movements", to=settings.AUTH_USER_MODEL, verbose_name="Registrado por")),
                ("recipient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="received_stock_movements", to=settings.AUTH_USER_MODEL, verbose_name="Destinatario")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="inventory.stockproduct", verbose_name="Producto")),
            ],
            options={
                "verbose_name": "Movimiento de stock",
                "verbose_name_plural": "Movimientos de stock",
                "ordering": ["-movement_date", "-created_at"],
                "constraints": [models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="stock_movement_quantity_positive")],
            },
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(fields=("product", "branch", "organizational_location"), name="unique_stock_balance_per_location"),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gte", 0)), name="stock_balance_quantity_nonnegative"),
        ),
    ]
