# Generated by Django 6.0.7 on 2026-08-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stockcategory_stockproduct_stockbalance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Compra"),
                    ("RETURN", "Devolución"),
                    ("INITIAL_ENTRY", "Ingreso inicial"),
                    ("DELIVERY", "Entrega"),
                    ("REPAIR", "Uso en reparación"),
                    ("CONSUMPTION", "Consumo"),
                    ("WRITE_OFF", "Baja"),
                    ("ADJUSTMENT", "Ajuste"),
                    ("POSITIVE_ADJUSTMENT", "Ajuste positivo"),
                    ("NEGATIVE_ADJUSTMENT", "Ajuste negativo"),
                    ("TRANSFER", "Transferencia"),
                    ("OTHER", "Otro"),
                ],
                max_length=20,
                verbose_name="Motivo",
            ),
        ),
    ]
