# Generated by Django 6.0.7 on 2026-09-25 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_technicianavailabilityrequest'),
        ('inventory', '0014_asset_technical_specifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Categoría')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Número de serie')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('LOANED', 'Prestada'), ('REPAIR', 'En reparación'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('LOST', 'Extraviada'), ('RETIRED', 'Dada de baja')], default='AVAILABLE', max_length=30, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inventory/tools/%Y/%m/', verbose_name='Fotografía')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='accounts.branch', verbose_name='Sede o planta')),
                ('organizational_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='inventory.organizationallocation', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ToolLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número')),
                ('borrower_name', models.CharField(blank=True, max_length=180, verbose_name='Nombre histórico del responsable')),
                ('loaned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de retiro')),
                ('expected_return_at', models.DateTimeField(verbose_name='Devolución prevista')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de devolución')),
                ('purpose', models.TextField(verbose_name='Motivo o destino')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones del préstamo')),
                ('return_observations', models.TextField(blank=True, verbose_name='Observaciones de devolución')),
                ('status', models.CharField(choices=[('ACTIVE', 'Prestada'), ('RETURNED', 'Devuelta'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_loans', to=settings.AUTH_USER_MODEL, verbose_name='Persona que retira')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_loans_delivered', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_loans_received', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.tool', verbose_name='Herramienta')),
            ],
            options={
                'verbose_name': 'Préstamo de herramienta',
                'verbose_name_plural': 'Préstamos de herramientas',
                'ordering': ['-loaned_at', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tool',), name='unique_active_tool_loan')],
            },
        ),
    ]
