# Generated by Django 6.0.7 on 2026-09-25 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_existing_tools_to_items(apps, schema_editor):
    ToolLoan = apps.get_model('inventory', 'ToolLoan')
    ToolLoanItem = apps.get_model('inventory', 'ToolLoanItem')

    ToolLoanItem.objects.bulk_create(
        ToolLoanItem(loan_id=loan.id, tool_id=loan.tool_id)
        for loan in ToolLoan.objects.all().iterator()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_tool_toolloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLoanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Herramienta del préstamo',
                'verbose_name_plural': 'Herramientas del préstamo',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='toolloan',
            name='unique_active_tool_loan',
        ),
        migrations.AddField(
            model_name='toolloanitem',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.toolloan', verbose_name='Préstamo'),
        ),
        migrations.AddField(
            model_name='toolloanitem',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_items', to='inventory.tool', verbose_name='Herramienta'),
        ),
        migrations.RunPython(
            copy_existing_tools_to_items,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='toolloan',
            name='tool',
        ),
        migrations.AddConstraint(
            model_name='toolloanitem',
            constraint=models.UniqueConstraint(fields=('loan', 'tool'), name='unique_tool_per_loan'),
        ),
    ]
