# Generated by Django 6.0.7 on 2026-09-27 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_returns(apps, schema_editor):
    loans = apps.get_model("inventory", "ToolLoan")
    items = apps.get_model("inventory", "ToolLoanItem")
    alias = schema_editor.connection.alias
    for loan in loans.objects.using(alias).filter(status="RETURNED").iterator():
        # Legacy headers can lack a return date; use their last recorded update.
        items.objects.using(alias).filter(loan_id=loan.pk).update(
            returned_at=loan.returned_at or loan.updated_at,
            received_by_id=loan.received_by_id,
            return_observations=loan.return_observations,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_toolloanitem_remove_toolloan_unique_active_tool_loan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolloanitem',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_loan_items_received', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por'),
        ),
        migrations.AddField(
            model_name='toolloanitem',
            name='return_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de devolución'),
        ),
        migrations.AddField(
            model_name='toolloanitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolución'),
        ),
        migrations.RunPython(copy_existing_returns, migrations.RunPython.noop),
    ]
