# Generated by Django 6.0.7 on 2026-09-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_toolloanitem_received_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='Asocie aquí un monitor con la CPU / unidad de sistema correspondiente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='inventory.asset', verbose_name='Equipo principal asociado'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('DESKTOP', 'CPU / Unidad de sistema'), ('LAPTOP', 'Notebook'), ('PRINTER', 'Impresora'), ('SCANNER', 'Escáner'), ('MONITOR', 'Monitor'), ('UPS', 'UPS'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('IP_PHONE', 'Teléfono IP'), ('OTHER', 'Otro')], default='DESKTOP', max_length=20, verbose_name='Tipo de equipo'),
        ),
    ]
