# Generated by Django 6.0.7 on 2026-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_asset_parent_asset_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('RECOVERED', 'Recuperado / Reacondicionado')], default='NEW', max_length=20, verbose_name='Condición del equipo'),
        ),
    ]
